---
- hosts: sv
  become: yes

  roles:
    - role: system

    - role: dotfiles
      when: enable_dotfiles

    - role: filesystems
      when: enable_filesystems

    - role: networking/connection
      when: enable_connection

    - role: networking/ddclient
      when: enable_ddclient

    - role: networking/nameserver
      when: enable_nameserver

    - role: networking/ssl
      when: enable_ssl

    - role: services/gitea
      when: enable_gitea

    - role: services/wiki
      when: enable_wiki

    - role: services/synapse
      when: enable_synapse

    - role: services/website
      when: enable_website

    - role: services/sftp
      when: enable_sftpr

    - role: services/mail
      when: enable_mail
