---
- hosts: sv
  become: yes

  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/set_host.yml
    - import_tasks: tasks/ssh_port.yml
    - import_tasks: tasks/bootstrap.yml

  roles:
    - role: system
    
    - role: filesystems
      when: enable_filesystems

    - role: networking/connection
      when: enable_connection

    - role: firewall
      when: enable_firewall

    - role: networking/ddclient
      when: enable_ddclient

    - role: networking/nameserver
      when: enable_nameserver

    - role: services/sftp
      when: enable_sftpr

    - role: services/mail
      when: enable_mail

    - role: networking/ssl
      when: enable_ssl

    - role: services/webserver
      when: enable_webserver

    - role: services/gitea
      when: enable_gitea

    - role: services/wiki
      when: enable_wiki

    - role: services/synapse
      when: enable_synapse

    - role: services/website
      when: enable_website

    - role: dotfiles
      when: enable_dotfiles
