- name: Cronjob to remove externally managed eth0 connection
  cron:
    name: "Ensure eth0 is not externally managed"
    minute: "*/10"
    job: "/usr/bin/nmcli connection down eth0 > /dev/null 2>&1; /usr/bin/nmcli connection down wired > /dev/null 2>&1; /usr/bin/nmcli connection up wired > /dev/null"
    state: present

- name: Enable cron daemon
  service:
    name: cronie
    state: started
    enabled: yes
