syncthing_user: syncthing
# group for file management
syncthing_group: vault
syncthing_guiaddress: 127.0.0.1:8080
syncthing_listen: tcp://0.0.0.0:22000
syncthing_localannounce: true
syncthing_globalannounce: true
syncthing_home: "/home/{{ syncthing_user }}"
syncthing_gui_user: "{{ syncthing_user }}"

# Paths for Syncthing folders
vault_path: "/mnt/disk/uv"
archive_path: "/mnt/disk/uva"

# Put this in the vault in cleartext: the playbook hashes it
syncthing_gui_pass: ""

# 22 chars for bcrypt
syncthing_gui_salt: "{{ lookup('password', '/dev/null chars=ascii_letters,digit length=22', seed=inventory_hostname) }}"

# Put this in host-vars or group-vars
# Follows conventions of Syncthing's REST API: see https://docs.syncthing.net/dev/rest.html
# But write in YAML.
syncthing_devices: []
#  - name: "Example Device"
#    deviceID: "AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA"
#  - name: "Main Device"
#    deviceID: "BBBBBBB-BBBBBBB-BBBBBBB-BBBBBBB-BBBBBBB-BBBBBBB-BBBBBBB-BBBBBBB"
#    introducer: true

# Also follows REST API convention
syncthing_folders: []
#  - label: "Example Folder"
#    id: "example"
#    path: "{{ syncthing_home }}/example/"

# Settings to add to all folders if not specified otherwise
# Separated into default folder settings, and default device settings
# Follows REST API convention
syncthing_defaults: {}
#  folder:
#    devices: "{{ syncthing_devices }}"
#    versioning:
#      type: "staggered"
#      params:
#        cleanoutDays: "60"
#        maxAge: "31536000"
#  device: {}
